apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8080
  selector:
    app: {{ .Chart.Name }}