apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: users-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
spec:
  hosts:
    - "*"
  gateways:
    - users-gateway
  http:
    - match:
        - uri:
            exact: /env1
        - uri:
            exact: /env2
      route:
        - destination:
            host: users
            port:
              number: 8080